schema_version = "1.0.0"

id = "assetfetch"
version = "0.3.0"
name = "AssetFetch For Blender"
tagline = "AssetFetch client for Blender"
maintainer = "ambientCG <hello@ambientCG.com>"
type = "add-on"
website = "https://assetfetch.org/"
tags = ["Pipeline"]
blender_version_min = "4.0.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

paths_exclude_pattern = [
   "__pycache__/",
   "/.git/",
   "/*.zip",
]